server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/customers
      
resilience4j.circuitbreaker:
    instances:
        creditCardsCB:
            #registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        
resilience4j.timelimiter:
    instances:
        creditCardsCB:
            timeoutDuration: 2s
            cancelRunningFuture: true

