server:
  port: 8006
topic:
    wallet:
        name: wallet
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/walletTransaction
